In [174]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder

In [175]:
dir = r"D:\Fernando\Escritorio\CRISP-DM\produccion_textil_CRISP-DM\data\tidy_data.csv"
data = pd.read_csv(dir)
data.dtypes

DATES                  object
DEPARTMENT             object
TEAM                    int64
SMV                   float64
WIP                     int64
OVER_TIME               int64
INCENTIVE               int64
IDLE_TIME               int64
IDLE_MEN                int64
NO_OF_STYLE_CHANGE      int64
NO_OF_WORKERS         float64
RATIO                 float64
dtype: object

In [176]:
data["DATES"] = pd.to_datetime(data["DATES"], format="%d/%m/%Y")
data.dtypes

DATES                 datetime64[ns]
DEPARTMENT                    object
TEAM                           int64
SMV                          float64
WIP                            int64
OVER_TIME                      int64
INCENTIVE                      int64
IDLE_TIME                      int64
IDLE_MEN                       int64
NO_OF_STYLE_CHANGE             int64
NO_OF_WORKERS                float64
RATIO                        float64
dtype: object

In [177]:
data_scaled = data.copy(deep=True)
for column in range(len(data_scaled.columns)):
    if column > 2:
        data_scaled.iloc[:, column] = preprocessing.MinMaxScaler().fit_transform( #StandardScaler
            data_scaled.iloc[:, column].values.reshape(-1,1))
data_scaled.head()

,DATES,DEPARTMENT,TEAM,SMV,WIP,OVER_TIME,INCENTIVE,IDLE_TIME,IDLE_MEN,NO_OF_STYLE_CHANGE,NO_OF_WORKERS,RATIO
0,2015-01-01,sweing,8,0.450252,0.047920,0.273148,0.027222,0.0,0.0,0.0,0.655172,0.122469
1,2015-01-01,finishing,1,0.020132,0.000000,0.037037,0.000000,0.0,0.0,0.0,0.068966,0.123320
2,2015-01-01,sweing,11,0.164731,0.041865,0.141204,0.013889,0.0,0.0,0.0,0.327586,0.098039
3,2015-01-01,sweing,12,0.164731,0.041865,0.141204,0.013889,0.0,0.0,0.0,0.327586,0.098039
4,2015-01-01,sweing,6,0.445219,0.050601,0.074074,0.013889,0.0,0.0,0.0,0.620690,0.098012

In [178]:
import pandas
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse=False)
data_encoded = encoder.fit_transform(data.iloc[:, 1:3])
feature_names = encoder.get_feature_names_out()
data_encoded = pd.DataFrame(data_encoded, columns=feature_names)
data_encoded

,DEPARTMENT_finishing,DEPARTMENT_sweing,TEAM_1,TEAM_2,TEAM_3,TEAM_4,TEAM_5,TEAM_6,TEAM_7,TEAM_8,TEAM_9,TEAM_10,TEAM_11,TEAM_12
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1192,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1193,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1194,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1195,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1196,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [179]:
dataset = pd.concat([data.iloc[:, 0], data_encoded, data_scaled.iloc[:, 3:12]], axis=1)
dataset

,DATES,DEPARTMENT_finishing,DEPARTMENT_sweing,TEAM_1,TEAM_2,TEAM_3,TEAM_4,TEAM_5,TEAM_6,TEAM_7,...,TEAM_12,SMV,WIP,OVER_TIME,INCENTIVE,IDLE_TIME,IDLE_MEN,NO_OF_STYLE_CHANGE,NO_OF_WORKERS,RATIO
0,2015-01-01,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.450252,0.047920,0.273148,0.027222,0.0,0.0,0.0,0.655172,0.122469
1,2015-01-01,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.020132,0.000000,0.037037,0.000000,0.0,0.0,0.0,0.068966,0.123320
2,2015-01-01,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.164731,0.041865,0.141204,0.013889,0.0,0.0,0.0,0.327586,0.098039
3,2015-01-01,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.164731,0.041865,0.141204,0.013889,0.0,0.0,0.0,0.327586,0.098039
4,2015-01-01,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.445219,0.050601,0.074074,0.013889,0.0,0.0,0.0,0.620690,0.098012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1192,2015-03-11,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.037037,0.000000,0.0,0.0,0.0,0.068966,0.075325
1193,2015-03-11,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.019357,0.000000,0.037037,0.000000,0.0,0.0,0.0,0.068966,0.083133
1194,2015-03-11,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.019357,0.000000,0.037037,0.000000,0.0,0.0,0.0,0.068966,0.092713
1195,2015-03-11,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.069444,0.000000,0.0,0.0,0.0,0.149425,0.052555
1196,2015-03-11,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.000000,0.000000,0.027778,0.000000,0.0,0.0,0.0,0.045977,0.037133

Modelo de machine learning

In [180]:
X_multiple = dataset.iloc[:, 1:23]
Y_multiple = dataset.iloc[:, 23]

In [181]:
from sklearn.model_selection import train_test_split
#Separo los datos de "train" en entrenamiento y prueba para probar los algoritmos
X_train, X_test, y_train, y_test = train_test_split(X_multiple, Y_multiple, test_size=0.05)

In [182]:
#Definimos el algoritmo a utilizar
from sklearn import linear_model
lr_multiple = linear_model.LinearRegression()

In [183]:
#Entrenamos el modelo
lr_multiple.fit(X_train, y_train)

LinearRegression()

In [184]:
#Realizamos una predicción
Y_pred_multiple = lr_multiple.predict(X_test)

In [185]:
print(lr_multiple.score(X_train, y_train))

0.07207952247751526