In [1]:
import pandas as pd
import numpy as np

In [2]:
dir = "Tidy_data.csv"
data = pd.read_csv(dir)
data.columns

Index(['DEPARTMENT', 'TEAM', 'TARGETED_PRODUCTIVITY', 'SMV', 'WIP',
       'OVER_TIME', 'INCENTIVE', 'IDLE_TIME', 'IDLE_MEN', 'NO_OF_STYLE_CHANGE',
       'NO_OF_WORKERS', 'ACTUAL_PRODUCTIVITY'],
      dtype='object')

In [6]:
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse=False)
data_encoded = encoder.fit_transform(data.iloc[:, 0:2])
feature_names = encoder.get_feature_names_out()
data_encoded = pd.DataFrame(data_encoded, columns=feature_names)
data_encoded

,DEPARTMENT_finishing,DEPARTMENT_sweing,TEAM_1,TEAM_2,TEAM_3,TEAM_4,TEAM_5,TEAM_6,TEAM_7,TEAM_8,TEAM_9,TEAM_10,TEAM_11,TEAM_12
0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1092,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1093,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1094,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1095,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1096,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [15]:
data_scaled = data.copy(deep=True)
for column in range(len(data_scaled.columns)):
    if column > 2 and column != 11:
        data_scaled.iloc[:, column] = preprocessing.MinMaxScaler().fit_transform( #StandardScaler
            data_scaled.iloc[:, column].values.reshape(-1,1))
data_scaled.head()

,DEPARTMENT,TEAM,TARGETED_PRODUCTIVITY,SMV,WIP,OVER_TIME,INCENTIVE,IDLE_TIME,IDLE_MEN,NO_OF_STYLE_CHANGE,NO_OF_WORKERS,ACTUAL_PRODUCTIVITY
0,finishing,1,0.75,0.020132,0.000000,0.064,0.000000,0.0,0.0,0.0,0.068966,0.886500
1,sweing,1,0.75,0.487418,0.252409,0.460,0.378151,0.0,0.0,0.0,0.637931,0.750428
2,finishing,2,0.75,0.020132,0.000000,0.064,0.000000,0.0,0.0,0.0,0.068966,0.755167
3,sweing,2,0.75,0.328494,0.271683,0.400,0.285714,0.0,0.0,0.0,0.609195,0.753098
4,sweing,3,0.75,0.487418,0.294663,0.460,0.378151,0.0,0.0,0.0,0.637931,0.753683

In [24]:
dataset = pd.concat([data_encoded, data_scaled.iloc[:, 2:12]], axis=1)
dataset

,DEPARTMENT_finishing,DEPARTMENT_sweing,TEAM_1,TEAM_2,TEAM_3,TEAM_4,TEAM_5,TEAM_6,TEAM_7,TEAM_8,...,TARGETED_PRODUCTIVITY,SMV,WIP,OVER_TIME,INCENTIVE,IDLE_TIME,IDLE_MEN,NO_OF_STYLE_CHANGE,NO_OF_WORKERS,ACTUAL_PRODUCTIVITY
0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.75,0.020132,0.000000,0.064,0.000000,0.0,0.0,0.0,0.068966,0.886500
1,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.75,0.487418,0.252409,0.460,0.378151,0.0,0.0,0.0,0.637931,0.750428
2,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.75,0.020132,0.000000,0.064,0.000000,0.0,0.0,0.0,0.068966,0.755167
3,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.75,0.328494,0.271683,0.400,0.285714,0.0,0.0,0.0,0.609195,0.753098
4,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.75,0.487418,0.294663,0.460,0.378151,0.0,0.0,0.0,0.637931,0.753683
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1092,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.75,0.366241,0.620460,0.400,0.285714,0.0,0.0,0.0,0.551724,0.750608
1093,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.80,0.000000,0.000000,0.160,0.000000,0.0,0.0,0.0,0.091954,0.874028
1094,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.80,0.164731,0.207561,0.228,0.420168,0.0,0.0,0.0,0.643678,0.800035
1095,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.80,0.032907,0.000000,0.144,0.000000,0.0,0.0,0.0,0.080460,0.922840
1096,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.80,0.239257,0.174203,0.272,0.529412,0.0,0.0,0.0,0.367816,0.800402

In [ ]:
dataset.to_csv('Encoded_data.csv', index=False)